### PR TITLE
Requeue the reconcile request on async update error

### LINKED ISSUE #176: Do not rely on status updates and consume DesiredStateChanged predicate
### What problem are you facing?

With https://github.com/crossplane/crossplane-runtime/pull/372, we have introduced a `DesiredStateChanged` to the xp runtime, which would filter out status update events.

However, upjet [relies on status updates](https://github.com/upbound/upjet/blob/615535f51088f690c02bbe0171c9a56d25acb45d/pkg/controller/api.go#L89) to re-queue after an async operation is completed. We need to fix it and consume `DesiredStateChanged` predicate.

### How could Upjet help solve your problem?

Do not rely on status updates and consume DesiredStateChanged predicate.

### LINKED ISSUE #180: Async failures are not retried with backoff
### What happened?

During the implementation of [this PR](https://github.com/upbound/upjet/pull/179), I realized that the current async operation callback mechanism does not back off after a failure with the current `APICallback` mechanism.

The main problem is when an async operation fails; there is no way to trigger a reconciliation **with backoff** since we are no longer inside the `Reconcile` method of controller-runtime; hence, we cannot use the existing backoff mechanisms coming with controller-runtime. As an example, think of the following scenario where we are trying to delete a non-empty s3 bucket:

1. Delete a non-empty bucket.
2. An async destroy operation started.
3. Async destroy failed -> we updated status (and annotations with [this PR](https://github.com/upbound/upjet/pull/179))
4. Resource is queued immediately, triggering a new reconciliation.
5. Go to step 2

As you can see from the above flow, we are not re-queuing with backoff, and there is no easy way to do so unless we implement our own mechanism somehow. 

### How can we reproduce it?

See the example flow above.

/cc @ulucinar @muvaf

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Fixes #176 
Fixes #180

This PR employs [the new `DesiredStatusChanged` predicate](https://github.com/crossplane/crossplane-runtime/pull/372) predicate from the crossplane-runtime as an event filter to prevent too-frequent reconciles on error conditions or on updates to the external create [pending](https://github.com/crossplane/crossplane-runtime/blob/4374a3b5d1ff58214b118a7cea641230bfbc785f/pkg/meta/meta.go#L45)/[failed](https://github.com/crossplane/crossplane-runtime/blob/4374a3b5d1ff58214b118a7cea641230bfbc785f/pkg/meta/meta.go#L59) annotations. It also allows the [async callback functions](https://github.com/upbound/upjet/blob/b70acc1bcb6d42499f0310b391f07694d0a97448/pkg/terraform/workspace.go#L131) to requeue a reconcile request with an exponential back-off, when the async operation fails. 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Tested the PR with https://github.com/upbound/provider-aws/pull/789.
When, for example, the external connector's `Connect` call fails, the requeue request is exponentially backed-off with a cap of 1 min. Here are the sample timestamps from an experiment with a `Connect` call failing:
```
2023-07-26T22:40:35+03:00
2023-07-26T22:40:36+03:00
2023-07-26T22:40:37+03:00
2023-07-26T22:40:41+03:00
2023-07-26T22:40:49+03:00
2023-07-26T22:41:05+03:00
2023-07-26T22:41:37+03:00
2023-07-26T22:42:37+03:00
2023-07-26T22:43:37+03:00
```

To test whether we exponentially back-off when we error in asynchronous callbacks, I provisioned an S3 bucket, put a file into it, and attempted to delete the bucket. Here are the timestamps belonging to the (failing) reconciliation attempts while deleting the `Bucket.s3` MR:
```
2023-07-26T23:03:35+03:00
2023-07-26T23:03:42+03:00
2023-07-26T23:03:48+03:00
2023-07-26T23:03:57+03:00
2023-07-26T23:04:06+03:00
2023-07-26T23:04:27+03:00
2023-07-26T23:05:04+03:00
2023-07-26T23:06:09+03:00
2023-07-26T23:07:14+03:00
2023-07-26T23:08:19+03:00
2023-07-26T23:09:24+03:00
2023-07-26T23:10:29+03:00
2023-07-26T23:11:34+03:00
```
, which again shows the reconcile requests are being exponentially backed-off.

We have also done some performance tests and those results can be found [here](https://github.com/upbound/upjet/pull/231#issuecomment-1652315774).

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/controller/api.go [hunk 1]
```diff
@@ -67,39 +74,109 @@ func NewAPICallbacks(m ctrl.Manager, of xpresource.ManagedKind) *APICallbacks {
...
+}
+
+func (e *eventHandler) Update(_ context.Context, _ event.UpdateEvent, _ workqueue.RateLimitingInterface) {
+}
+
+func (e *eventHandler) Delete(_ context.Context, _ event.DeleteEvent, _ workqueue.RateLimitingInterface) {
+}
+
+func (e *eventHandler) Generic(_ context.Context, _ event.GenericEvent, _ workqueue.RateLimitingInterface) {
+}
```
Comment (sergenyalcin) [inline pkg/controller/api.go:182]: As we discussed offline, we may consider copying the same logic in the `(e *eventHandler) Create` to other interface implementations.

**Review by sergenyalcin — COMMENTED** [review]
Thanks @ulucinar these are my comments.

File: pkg/controller/api.go [hunk 2]
```diff
@@ -67,39 +74,109 @@ func NewAPICallbacks(m ctrl.Manager, of xpresource.ManagedKind) *APICallbacks {
...
 		tr.SetConditions(resource.AsyncOperationFinishedCondition())
-		return errors.Wrap(ac.kube.Status().Update(ctx, tr), errStatusUpdate)
+		return errors.Wrapf(ac.kube.Status().Update(ctx, tr), errUpdateStatusFmt, tr.GetObjectKind().GroupVersionKind().String(), name, op)
 	}
 }
 
-// Destroy makes sure the error is saved in async operation condition.
-func (ac *APICallbacks) Destroy(name string) terraform.CallbackFn {
+// Create makes sure the error is saved in async operation condition.
+func (ac *APICallbacks) Create(name string) terraform.CallbackFn {
```
[the remark this answers is not in the document]
Comment (ulucinar) [reply pkg/controller/api.go:124]: Done. Refactored the requeue logic into the `controller.callbackFn` function. In the context of `controller.CallbackProvider`, I think it's good to have an interface reflecting the logical functions (async create/update/delete) instead of the implementation specific functions (both create and update are implemented via a `terraform apply`). In the feature, for example, we may want to explore different service classes for the create & create operations, e.g., we may want to prioritize async create operations over update operations if we want to optimize certain metrics for example.

File: pkg/controller/api.go (hunk 1 above)
Comment (ulucinar) [reply pkg/controller/api.go]: Agreed. The previous assumption is that event handler's `Create` will always be called for the controller. But we don't know if this is true. Let's assume less and do some more synchronization.

**Comment by ulucinar** [comment]
Done a set of measurements with this PR. While this PR mainly decreases the resource utilization in case of especially when the external connector (or client) fails fast in the `Connect` call by properly doing exponential back-off, I'm posting the measurements with `index.docker.io/ulucinar/provider-aws:v0.38.0-rc.0.18.gca9398d9` below for reference.

```
------------------------------------------------------------
INFO[0040] Experiment Duration: 40.048828 seconds
INFO[0100] Average Time to Readiness of Repository: 12.800000 seconds
INFO[0100] Peak Time to Readiness of Repository: 16.000000 seconds
INFO[0100] Pod: provider-aws-8d35452277a1-5c48fd696d-wklhf
INFO[0100] Average Memory: 661039894.811881 Bytes
INFO[0100] Peak Memory: 1248210944.000000 Bytes
INFO[0100] Pod: provider-aws-8d35452277a1-5c48fd696d-wklhf
INFO[0100] Average CPU: 12.935712 Rate
INFO[0100] Peak CPU: 16.035185 Rate
------------------------------------------------------------
INFO[0039] Experiment Duration: 39.268071 seconds
INFO[0099] Average Time to Readiness of Repository: 13.400000 seconds
INFO[0099] Peak Time to Readiness of Repository: 16.000000 seconds
INFO[0099] Pod: provider-aws-8d35452277a1-5c48fd696d-jkc4g
INFO[0099] Average Memory: 402984069.565217 Bytes
INFO[0099] Peak Memory: 545832960.000000 Bytes
INFO[0099] Pod: provider-aws-8d35452277a1-5c48fd696d-jkc4g
INFO[0099] Average CPU: 16.826778 Rate
INFO[0099] Peak CPU: 19.651389 Rate
------------------------------------------------------------
INFO[0040] Experiment Duration: 40.004987 seconds
INFO[0100] Average Time to Readiness of Repository: 12.600000 seconds
INFO[0100] Peak Time to Readiness of Repository: 16.000000 seconds
INFO[0100] Pod: provider-aws-8d35452277a1-5c48fd696d-9wkpm
INFO[0100] Average Memory: 536236977.230769 Bytes
INFO[0100] Peak Memory: 793706496.000000 Bytes
INFO[0100] Pod: provider-aws-8d35452277a1-5c48fd696d-9wkpm
INFO[0100] Average CPU: 17.463247 Rate
INFO[0100] Peak CPU: 20.957870 Rate
```

**Comment by ulucinar** [comment]
> Thanks, @ulucinar. These are my comments. According to the results in the description, deletion times seem to be getting longer. How would you like to handle this?

Did some refactoring and repeated the tests [here](https://github.com/upbound/upjet/pull/231#issuecomment-1652315774). I think the experiments with 5 MRs have high variance but still the total experiment times are around the expected values.

**Comment by sergenyalcin** [comment]
Some performance test results. There are improvements with this PR.

**_v0.37.0 AWS Monolithic Test Results_**

(1) INFO[0683] Results - v0.37.0 - AWS - 100 ECR Repository
INFO[0683] Experiment Duration: 683.665586 seconds
INFO[0744] Average Time to Readiness of Repository: 158.760000 seconds
INFO[0744] Peak Time to Readiness of Repository: 449.000000 seconds
INFO[0744] Average Memory Working Set: 1793215686.011050 Bytes
INFO[0744] Peak Memory Working Set: 2998583296.000000 Bytes
INFO[0744] Average CPU Utilisation: 74.995274 Rate
INFO[0744] Peak CPU Utilisation: 96.572685 Rate

(2) INFO[0776] Results - v0.37.0 - AWS - 100 ECR Repository
INFO[0776] Experiment Duration: 776.977605 seconds
INFO[0837] Average Time to Readiness of Repository: 171.840000 seconds
INFO[0837] Peak Time to Readiness of Repository: 512.000000 seconds
INFO[0837] Average Memory Working Set: 1681988067.894988 Bytes
INFO[0837] Peak Memory Working Set: 3320328192.000000 Bytes
INFO[0837] Average CPU Utilisation: 77.289236 Rate
INFO[0837] Peak CPU Utilisation: 97.487037 Rate

(3) INFO[0783] Results - v0.37.0 - AWS - 100 ECR Repository
INFO[0783] Experiment Duration: 783.135806 seconds
INFO[0844] Average Time to Readiness of Repository: 170.790000 seconds
INFO[0844] Peak Time to Readiness of Repository: 514.000000 seconds
INFO[0844] Average Memory Working Set: 1671129672.086643 Bytes
INFO[0844] Peak Memory Working Set: 3548098560.000000 Bytes
INFO[0844] Average CPU Utilisation: 87.594181 Rate
INFO[0844] Peak CPU Utilisation: 97.258333 Rate


**_AWS Monolithic Test Results from this branch_**

(1) INFO[0351] Results - index.docker.io/ulucinar/provider-aws:v0.38.0-rc.0.43.g24291c953 - AWS - 100 ECR Repository
INFO[0351] Experiment Duration: 351.023854 seconds      
INFO[0411] Average Time to Readiness of Repository: 118.950000 seconds  
INFO[0411] Peak Time to Readiness of Repository: 158.000000 seconds  
INFO[0411] Average Memory Working Set: 1801325607.766990 Bytes  
INFO[0411] Peak Memory Working Set: 4295589888.000000 Bytes  
INFO[0411] Average CPU Utilisation: 58.053456 Rate      
INFO[0411] Peak CPU Utilisation: 95.928241 Rate

(2) INFO[0361] Results - index.docker.io/ulucinar/provider-aws:v0.38.0-rc.0.43.g24291c953 - AWS - 100 ECR Repository
INFO[0361] Experiment Duration: 361.475772 seconds      
INFO[0422] Average Time to Readiness of Repository: 124.750000 seconds  
INFO[0422] Peak Time to Readiness of Repository: 164.000000 seconds  
INFO[0422] Average Memory Working Set: 1712672535.052133 Bytes  
INFO[0422] Peak Memory Working Set: 3577266176.000000 Bytes  
INFO[0422] Average CPU Utilisation: 58.469990 Rate      
INFO[0422] Peak CPU Utilisation: 94.883796 Rate 

(3) INFO[0370] Results - index.docker.io/ulucinar/provider-aws:v0.38.0-rc.0.43.g24291c953 - AWS - 100 ECR Repository
INFO[0370] Experiment Duration: 370.100280 seconds      
INFO[0430] Average Time to Readiness of Repository: 125.030000 seconds  
INFO[0430] Peak Time to Readiness of Repository: 171.000000 seconds  
INFO[0430] Average Memory Working Set: 1889391200.222738 Bytes  
INFO[0430] Peak Memory Working Set: 3654717440.000000 Bytes  
INFO[0430] Average CPU Utilisation: 58.346910 Rate      
INFO[0430] Peak CPU Utilisation: 91.258796 Rate
