### PR TITLE
Escape CEL Reserved Keywords when Generating Validation Rules

### LINKED ISSUE #254: Escape CEL Reserved Keywords in Validation Rules
### What happened?
When generating code for a Terraform resource that has a field matching a CEL reserved keyword (e.g., [rancher2_app_v2](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/app_v2) contains `namespace`), the generated CRD fails to apply with the following message.
```
The CustomResourceDefinition "appv2s.app.rancher2.upbound.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].x-kubernetes-validations[2].rule: Invalid value: apiextensions.ValidationRule{Rule:"self.managementPolicy == 'ObserveOnly' || has(self.forProvider.namespace)", Message:"namespace is a required parameter"}: compilation failed: ERROR: <input>:1:46: undefined field 'namespace'
 | self.managementPolicy == 'ObserveOnly' || has(self.forProvider.namespace)
 | .............................................^
```

### How can we reproduce it?
Can be reproduced by performing the following steps:
- Using the [upjet-provider-template](https://github.com/upbound/upjet-provider-template)
- Point the code at a resource with a field that matches a CEL reserved keyword (e.g., [rancher2_app_v2](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/app_v2) contains `namespace`)
- Run `make generate`
- Run `kubectl apply -f package/crds`

### Fix
Will open a fix shortly. Fix wraps the `ValidationRule` field name references in `__` (e.g., `__namespace__`). For reference, search for "escape sequence" on the [K8s CRD page](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules).

### PR DESCRIPTION
**Pull request by dalton-hill-0**
### Description of your changes

Fixes #254

Wraps CEL reserved keywords found in Validation Rules (i.e., `__{keyword}__`).

For instance, if the object has a field "namespace", this would be the before and after in `zz_<obj>_types.go`
```diff
- // +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.namespace)",message="namespace is a required parameter"
+ // +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.__namespace__)",message="namespace is a required parameter"
```

The same diff, for the generated CRD
```diff
            x-kubernetes-validations:
            - message: namespace is a required parameter
-             rule: self.managementPolicy == 'ObserveOnly' || has(self.forProvider.namespace)
+             rule: self.managementPolicy == 'ObserveOnly' || has(self.forProvider.__namespace__)
```

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

- Updated existing unit tests to include Validation Rules.
- Manually wrapped code in generated CRDs to ensure the escaping actually resolves the issue.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by dalton-hill-0** [comment]
PR is ready for review
@ulucinar @sergenyalcin

File: pkg/types/builder_test.go [hunk 1]
```diff
@@ -394,6 +433,9 @@ func TestBuild(t *testing.T) {
 					t.Fatalf("Build(...): -want atProvider, +got atProvider: %s", diff)
 				}
 			}
+			if diff := cmp.Diff(tc.want.validationRules, g.ValidationRules, test.EquateErrors()); diff != "" {
```
Comment (lsviben) [inline pkg/types/builder_test.go:436]: `test.EquateErrors()` is not needed here, probably also not needed above.

```suggestion
			if diff := cmp.Diff(tc.want.validationRules, g.ValidationRules); diff != "" {
```

**Review by lsviben — APPROVED** [review]
Minor comment, otherwise LGTM. Thanks @dalton-hill-0 for the contribution!

File: pkg/types/builder_test.go (hunk 1 above)
Comment (dalton-hill-0) [reply pkg/types/builder_test.go]: Thanks @lsviben 

I have removed `test.EquateErrors()` from the string comparisons.

File: pkg/types/builder.go [hunk 2]
```diff
@@ -444,3 +455,12 @@ func fieldPathWithWildcard(parts []string) string {
 	}
 	return seg.String()
 }
+
+func sanitizePath(p string) string {
```
Comment (ulucinar) [inline pkg/types/builder.go:459]: nit:
```suggestion
func escapeName(p string) string {
```
