### PR TITLE
Filter failed "terraform init" output for sensitive information

### LINKED ISSUE #154: Secrets leakage when describing failing resource
### What happened?
While developing a new resource in a provider i got this when describing a failing resource i get return (next to the 'normal info')
```
> k describe repositoryfile sample-file.txt

Name:         sample-file.txt
Namespace:
Labels:       <none>
Annotations:  crossplane.io/external-name: sample-file.txt
API Version:  repo.github.upbound.io/v1alpha1
Kind:         RepositoryFile
Metadata:
  Creation Timestamp:  2023-02-03T09:24:31Z

... skipped info by me

Status:
  At Provider:
  Conditions:
    Last Transition Time:  2023-02-03T09:25:53Z
    Message:               connect failed: cannot get a terraform workspace for resource: cannot init workspace: There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Invalid resource name
│
│   on main.tf.json line 1, in resource.github_repository_file:
│    1: {"provider":{"github":{"owner":"**redacted**","token":"***redacted***"}},"resource":{"github_repository_file":{"sample-file.txt":{"branch":"add-file-branch","commit_author":"Crossplane Github Provider","commit_email":"github-provider@crossplane.com","commit_message":"managed by crossplane provider","content":"I am an crossplane \nprovider. This should be nice.\n","file":"sample-file.txt","lifecycle":{"prevent_destroy":true},"name":"sample-file.txt","repository":"github-crossplane-file-test"}}},"terraform":{"required_providers":{"github":{"source":"integrations/github","version":"5.15.0"}}}}
│
│ A name must start with a letter or underscore and may contain only letters,
│ digits, underscores, and dashes.
╵

: exit status 1
```

The issue here is that the full `main.tf.json` and this file as potentially secrets in there. 

### How can we reproduce it?

* Create a provider using upjet
* Create a resource which does not have the `name` input
* configure externalname with `config.NameAsIdentifier`
* Run the provider locally (`make run`) 
* Deploy the resource with an invalid nameing pattern (non dns spec)
* Describe the failing resource

### What environment did it happen in?
Crossplane version: docker.io/upbound/crossplane:v1.10.2-up.1

* Kubernetes version: 1.25
* Kind
* Mac OS 12.6.1

> initially opened an issue at crossplane here: https://github.com/crossplane/crossplane/issues/3721

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Fixes #154 

This PR proposes a change for redacting sensitive information in `terraform init` output when debug-level logging or when updating the `status.conditions` of an MR.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Tested against https://github.com/coopnorge/provider-github/pull/6. Following `status.condition` is now reported with redacted sensitive information:
```yaml
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2023-02-06T21:30:40Z"
    message: "connect failed: cannot get a terraform workspace for resource: cannot
      init workspace: \e[31m\e[0mThere are some problems with the configuration, described
      below.\n\nThe Terraform configuration must be valid before initialization so
      that\nTerraform can determine which modules and providers need to be installed.\e[0m\e[0m\n\e[31m\e[31m╷\e[0m\e[0m\n\e[31m│\e[0m
      \e[0m\e[1m\e[31mError: \e[0m\e[0m\e[1mInvalid resource name\e[0m\n\e[31m│\e[0m
      \e[0m\n\e[31m│\e[0m \e[0m\e[0m  on main.tf.json line 1, in resource.github_repository_file:\n\e[31m│\e[0m
      \e[0m   1: {\"provider\":{\"github\":{\"base_url\":\"REDACTED\",\"owner\":\"REDACTED\",\"REDACTED\":\"REDACTED\"}},\"resource\":{\"github_repository_file\":{\e[4m\"sample-file.txt\"\e[0m:{\"content\":\"HO.\",\"file\":\"test-file\",\"lifecycle\":{\"prevent_destroy\":true},\"name\":\"sample-file.txt\"}}},\"terraform\":{\"required_providers\":{\"github\":{\"source\":\"integrations/github\",\"version\":\"5.15.0\"}}}}\e[0m\n\e[31m│\e[0m
      \e[0m\n\e[31m│\e[0m \e[0mA name must start with a letter or underscore and may
      contain only letters,\n\e[31m│\e[0m \e[0mdigits, underscores, and dashes.\n\e[31m╵\e[0m\e[0m\n\e[0m\e[0m\n:
      exit status 1"
    reason: ReconcileError
    status: "False"
    type: Synced
```

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: pkg/terraform/workspace.go [hunk 1]
```diff
@@ -111,16 +121,16 @@ func (w *Workspace) ApplyAsync(callback CallbackFn) error {
 		cmd.SetEnv(append(os.Environ(), w.env...))
 		cmd.SetDir(w.dir)
 		out, err := cmd.CombinedOutput()
+		if err != nil {
```
Comment (sergenyalcin) [inline pkg/terraform/workspace.go:124]: I think we are converting a possible error from CombinedOutput to the format of the Apply error before passing it to the callback function. This seems like an improvement to the logs.

File: pkg/terraform/workspace.go [hunk 2]
```diff
@@ -176,16 +186,16 @@ func (w *Workspace) DestroyAsync(callback CallbackFn) error {
...
```
Comment (sergenyalcin) [inline pkg/terraform/workspace.go:189]: I think we are converting a possible error from CombinedOutput to the format of the Destroy error before passing it to the callback function. This seems like an improvement to the logs.

**Review by sergenyalcin — APPROVED** [review]
Thanks @ulucinar LGTM!

File: pkg/terraform/workspace.go (hunk 1 above)
Comment (ulucinar) [reply pkg/terraform/workspace.go:124]: Hi @sergenyalcin,
Yes, correct. In the synchronous invocations of these commands, we are already transforming the errors so that we do not accidentally leak sensitive info:
https://github.com/upbound/upjet/blob/aeb5f15054f18d0eff52a75e71ec0f562fb79ffb/pkg/terraform/workspace.go#L144

But looks like currently this is not the case in asynchronous invocations.

File: pkg/terraform/workspace.go (hunk 2 above)
Comment (ulucinar) [reply pkg/terraform/workspace.go:189]: Hi @sergenyalcin,
Yes, correct. As in the synchronous invocations of these commands, we are transforming the errors so that we do not accidentally leak sensitive info:
https://github.com/upbound/upjet/blob/aeb5f15054f18d0eff52a75e71ec0f562fb79ffb/pkg/terraform/workspace.go#L144

These changes improve the readability in my opinion.
